### PR TITLE
install.sh usability fixes

### LINKED ISSUE #2523: Installation usability test - high priority issues
## Problem

We did a round of usability testing on the `install.sh`; issues were found. This issue collects the feedback together. 

### Code
- [x] ~User should press ENTER at the `DOCKER SETUP` step so they have time to read.~ Not sure what this means.
- [x] Multiple people have reported not being able to log in or not being able to create a schema once logged in. Please verify this works. (Note from @kgodey: we have root SSH access + admin user access to this instance, if it will help debug).
- [x] Determine how `admin` user is being created in prod installation setup. This is causing a bug if the user also tries to create a superuser named `admin`.
- [x] Use proper user for `pg_isready` to avoid `FATAL:  role "root" does not exist` spam in logs.
- [x] Figure out warning when starting containers:
  `RequestsDependencyWarning: urllib3 (1.26.14) or chardet (5.1.0)/charset_normalizer (2.0.7) doesn't match a supported version!`

### Copy
- [x] ~Make some troubleshooting items into prerequisites (e.g., docker versions)~ Already fixed
- [x] Change "terminal window" -> "terminal" in docs - Fixed in #2549 
- [x] ~Format important words in documentation specially~ - Unclear what "important" means
- [x] ~Make separate section with description of files output by `install.sh` (environment file)~ - Already fixed
- [x] ~Add separate "Maintenance" section in docs for upgrades and so on.~ - New "Administration" section under "Installation" should fix this.

### Notes
- #2550 was pulled out from here.
- Styling related issues are tracked in #2457 
- Some issues pulled into #2570

### PR DESCRIPTION
**Pull request by silentninja**
Related to #2523 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -312,7 +312,12 @@ printf "
 Service is ready and healthy!
 Adding admin user to Django webservice now.
 "
-sudo docker exec mathesar_service python manage.py createsuperuser --no-input --username "$superuser_username" --email "$superuser_email" 2> >(grep -vi warn)
+while !  sudo docker exec mathesar_service python manage.py createsuperuser --no-input --username "$superuser_username" --email "$superuser_email"
+do
+  read -r -p "Choose a different admin username [mathesar]: " superuser_username
```
Comment (kgodey) [inline install.sh:317]: Please change the default username to `admin`

Comment (mathemancer) [reply install.sh:331]: With this fix, that won't work. I.e., this fix essentially just prompts a user to create a different user if the username is already taken. The username in question, in this case, is `admin`. We would assume that's already taken, since we still don't know how it's being created.

I suggest we remove this change, and merge the other changes to get those fixes in.

**Review by mathemancer — CHANGES_REQUESTED** [review]
I think we should remove the changes to the `install.sh` script, and keep the other changes.

**Comment by silentninja** [comment]
> I think we should remove the changes to the install.sh script, and keep the other changes.
@mathemancer Even though we added the prompt to ask for different super username in case it conflicts with existing user to fix a bug which we cannot reproduce. We also want the install.sh to be idempotent.

**Review by mathemancer — APPROVED** [review]
After discussion with @silentninja and doing some of my own poking around, the `admin` username already being created bug appears to have disappeared on its own.

Given some other issues with silently passing over the `admin` name already existing, we're going to merge this without the fix on that.

**Comment by mathemancer** [comment]
> @mathemancer Even though we added the prompt to ask for different super username in case it conflicts with existing user to fix a bug which we cannot reproduce, we also want the install.sh to be idempotent.

Let's handle that separately. We need some care when handling user input in that case.

**Comment by silentninja** [comment]
>  the admin username already being created bug appears to have disappeared on its own.

The only scenario where I had `the admin username already being created` bug  was when I changed from development mode to production mode. This is warranted as we create a `admin` user automatically in development mode.
