### PR TITLE
Properly detect identity columns

### LINKED ISSUE #3124: Couldn't create new rows for the tables that use IDENTITY for their id columns.
## Description

We have moved to using a different method for ids generations for our default id column as discussed [here](https://github.com/centerofci/mathesar/pull/3016), however this results in an inablility to create new rows using the ui.

Screenshot from 2023-08-02 17-23-18

For some reason the call to the `records/` api isn't being made. Using the browsable api works as expected.

## Expected behavior

We should be able to use the ui to create rows for this kind of tables. 

## To Reproduce

- Create a new table using the psql shell: `SELECT msar.add_mathesar_table(2200, 'test_table', NULL, NULL, NULL);` <-- This will create a new table in your `public` shema.
- Sync external changes.
- Try to add new rows to that table.

### PR DESCRIPTION
**Pull request by mathemancer**
Fixes #3124 

This corrects the detection of columns marked as `GENERATED BY DEFAULT AS IDENTITY` as having a dynamic default.

**Technical details**

Irritatingly, PostgreSQL doesn't actually note such columns in the `pg_attrdef` table (where you'd usually find column defaults), and SQLAlchemy doesn't wrap those defaults in a `DefaultClause` so SQLAlchemy also doesn't really detect them properly.

Regardless, we now note that these columns have a default, which we simply call `'identity'` in the Python layer, and we mark that default as dynamic.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the `develop` branch of the repository
- [X] My commit messages follow [best practices][best_practices].
- [X] My code follows the established code style of the repository.
- [X] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: db/sql/0_msar.sql [hunk 1]
```diff
@@ -272,9 +272,17 @@ Args:
...
-WHERE adrelid=tab_id AND adnum=col_id;
+SELECT
+  -- This is a typical dynamic default like NOW() or CURRENT_DATE
+  (split_part(substring(adbin, 2), ' ', 1) IN (('SQLVALUEFUNCTION'), ('FUNCEXPR')))
+  OR
+  -- This is an identity column `GENERATED {ALWAYS | DEFAULT} AS IDENTITY`
+  (attidentity <> '')
+  OR
+  -- Other generated columns show up here.
+  (attgenerated <> '')
```
Comment (Anish9901) [inline db/sql/0_msar.sql:283]: Nice!

**Review by Anish9901 — APPROVED** [review]
Working as expected @mathemancer, Thanks!
