### PR TITLE
Fix nested buttons and overflow issue in constraints modal

### LINKED ISSUE #2101: Eliminate nested buttons in Constraints modal
## Problem

- In the Constraints modal (accessible via the "Advanced" section of the table inspector), we have two nested buttons

    image

- Nested buttons are bad for a11y and also mean that when you click on the trash icon, the constraint expands.

## Solution

- We should remove the nesting.

- We should make changes to the `Collapsible` component to support an additional slot (named "trigger-aside") that gets placed alongside the trigger button.

- `ConstraintTypeSection` and `ConstraintCollapseHeader` should get refactored to move the trash button into the "trigger-aside" slot.

- The resulting buttons should be alongside each other, no longer be nested, like this:

    image

### LINKED ISSUE #2102: Improve handling of overflow in constraints modal
In the Constraints modal, overflow of long constraint headers obscures information and causes the delete button to disappear.

image

We should fix this by adding wrapping and/or truncation.

Notes

- The HTML is slated to be slightly rearranged in #2101 which should hopefully fix the button problem. But we'll still need to ensure we can see all the columns somehow.

- We have a `Truncate` component which is already in-use here. To fix this issue via truncation, we'll need to set `overflow: hidden` on some parent elements appropriately.

### PR DESCRIPTION
**Pull request by SumeetHaryani**
Fixes  #2101 and fixes #2102 

**Technical details**

- Updated `Collapsible` component to support an additional slot (named "trigger-aside")
- Refactored `ConstraintTypeSection` and `ConstraintCollapseHeader` components 
- Fixed overflow issue in constraints modal
**Screenshots**

Screenshot from 2023-01-21 22-48-12
image

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by rajatvijay** [comment]
@SumeetHaryani looks like there are some TS error which is making the `typecheck` script fail in GitHub actions. Can you fix that please.

**Comment by SumeetHaryani** [comment]
@rajatvijay I have added a fix for this. Can you please re-run the workflow once

**Comment by SumeetHaryani** [comment]
Hey @rajatvijay, any update here?

**Comment by rajatvijay** [comment]
Hi @SumeetHaryani. Sorry for the delay here, have been out. I will review this today.

File: mathesar_ui/src/component-library/collapsible/Collapsible.svelte [hunk 1]
```diff
@@ -6,29 +6,32 @@
...
+        <Icon
+          {...iconExpandDown}
+          size="0.9rem"
+          rotate={isOpen ? undefined : 270}
+        />
+        <div class="collapsible-header-title">
+          <slot name="header" />
+        </div>
+      </Button>
+      <slot name="trigger-aside" />
```
Comment (rajatvijay) [inline mathesar_ui/src/component-library/collapsible/Collapsible.svelte:31]: The `trigger-aside` slot should be outside the `trigger` slot. This way the user can have a custom trigger as well as use the `trigger-aside` slot.

File: mathesar_ui/src/component-library/collapsible/Collapsible.scss [hunk 2]
```diff
@@ -3,25 +3,29 @@
...
-    &.focus {
-      box-shadow: none;
+    justify-content: space-between;
+    .collapsible-header-btn {
+      display: flex;
+      width: 100%;
+      text-align: left;
+      cursor: pointer;
+      font-weight: inherit;
+      align-items: flex-start;
```
Comment (rajatvijay) [inline mathesar_ui/src/component-library/collapsible/Collapsible.scss:13]: This particular CSS seems to be causing icon misalignment here: 
Screenshot 2023-01-31 at 12 14 44 AM

File: mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte [hunk 3]
```diff
@@ -53,10 +35,9 @@
   .column-names {
     display: flex;
     flex-direction: row;
-
-    > :global(* + *) {
-      margin-left: 0.25rem;
-    }
+    flex-wrap: wrap;
+    justify-content: flex-start;
+    gap: 0.25rem;
```
Comment (rajatvijay) [inline mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte:40]: We are trying to use this property because of less support in the Safari browser. You can use the owl selector in conjunction with `:global`. Something like: 

```css
> :global(* + *) {
    margin-left: 0.25rem;
}
```

**Review by rajatvijay — CHANGES_REQUESTED** [review]
Nice work @SumeetHaryani ⭐ 

Requested a few minor changes. Feel free to reach out for any questions that you have 😄

File: mathesar_ui/src/component-library/collapsible/Collapsible.scss (hunk 2 above)
Comment (SumeetHaryani) [reply mathesar_ui/src/component-library/collapsible/Collapsible.scss]: Fixed icon misalignment issue
Screenshot from 2023-01-31 22-35-51

File: mathesar_ui/src/component-library/collapsible/Collapsible.svelte (hunk 1 above)
Comment (SumeetHaryani) [reply mathesar_ui/src/component-library/collapsible/Collapsible.svelte]: Moved` trigger-aside` slot should be outside the `trigger` slot

File: mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte (hunk 3 above)
Comment (SumeetHaryani) [reply mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte]: updated and avoided the use of gap property here

**Comment by kgodey** [comment]
@SumeetHaryani Please make sure to re-request review once requested changes are addressed.

**Review by rajatvijay — CHANGES_REQUESTED** [review]
The alignment still looks off. 
Screenshot 2023-02-02 at 5 33 36 PM

### I suggest the following changes:

**To make the delete icon align vertically in the center:** 

Add the following CSS to the `collapsible-header` class
```css
 align-items: center;
```

**To make the chevron icon vertically aligned:** 

Remove the following CSS from the `collapsible-header-icon` class
```css
 align-self:flex-start;
 margin-top:0.18rem;
```

**To give vertical space between multiple `column-name-container`s:** 

Add `margin-bottom: 0.285rem;` to the `column-name-container` class and add `margin-bottom: -0.285rem;` to the flex container having `column-names` class. 
Remember to use css-variables for the margin value to always keep the positive and the negative margins in sync. 

**To give horizontal space between multiple `column-name-container`s:**

Use the owl selector(shown below) on their flex parent with the `column-names` class
```css
> :global(* + *) {
      margin-left: 0.25rem;
    }
```

File: mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte [hunk 4]
```diff
@@ -53,16 +35,16 @@
   .column-names {
     display: flex;
     flex-direction: row;
-
-    > :global(* + *) {
-      margin-left: 0.25rem;
-    }
+    -webkit-flex-wrap: wrap;
+    flex-wrap: wrap;
+    -ms-flex-wrap: wrap;
```
Comment (rajatvijay) [inline mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte:40]: `flex-wrap` seems pretty [supported without a vendor prefix](https://caniuse.com/mdn-css_properties_flex-wrap). I think its safe to remove them.

**Review by rajatvijay — CHANGES_REQUESTED** [review]
Added one more minor comment:

File: mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte (hunk 4 above)
Comment (SumeetHaryani) [reply mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte]: Removed and updated

**Comment by SumeetHaryani** [comment]
> The alignment still looks off. Screenshot 2023-02-02 at 5 33 36 PM
> 
> ### I suggest the following changes:
> **To make the delete icon align vertically in the center:**
> 
> Add the following CSS to the `collapsible-header` class
> 
> ```css
>  align-items: center;
> ```
> 
> **To make the chevron icon vertically aligned:**
> 
> Remove the following CSS from the `collapsible-header-icon` class
> 
> ```css
>  align-self:flex-start;
>  margin-top:0.18rem;
> ```
> 
> **To give vertical space between multiple `column-name-container`s:**
> 
> Add `margin-bottom: 0.285rem;` to the `column-name-container` class and add `margin-bottom: -0.285rem;` to the flex container having `column-names` class. Remember to use css-variables for the margin value to always keep the positive and the negative margins in sync.
> 
> **To give horizontal space between multiple `column-name-container`s:**
> 
> Use the owl selector(shown below) on their flex parent with the `column-names` class
> 
> ```css
> > :global(* + *) {
>       margin-left: 0.25rem;
>     }
> ```


@rajatvijay Added the above changes
