### PR TITLE
Set up modal confirmation system

### LINKED ISSUE #755: Improvements for table deletion flow
## Description
From the PR https://github.com/centerofci/mathesar/pull/650, we identified certain improvements we could do for the UX for deleting table.

Quoting points from this comment: https://github.com/centerofci/mathesar/pull/650#pullrequestreview-787938023
* Show loading inside the modal when deletion is in progress
* Close the modal only after deletion completes
* Keep modal open, if the delete request fails. Show error inside the modal.
* Always ask for confirmation (by opening the modal), when user clicks delete. Right now, it is only shown when the table has dependencies (which is usually always the case).

Our existing UX does not cover loading and failure states. These are minor changes that keep the same flow and handle the missing states.

@ghislaineguerin Please take a look and update if this looks good or if we need a fundamental change in the UX.

### LINKED ISSUE #759: Build a more ergonomic abstraction for UI confirmation modals
## Problem

- Currently displaying a modal confirmation message is a lot of work. 
- When adding a new modal confirmation, I don't want to have to touch the template section of any components. I definitely don't want to create any new components.

## End goal

- Example for the most common case:

    Within the `<script>` of a component

    ```ts
    async function handleDeleteTable(id: number): void {
      const isConfirmed = await confirm({
        title: 'Delete Table',
        message: 'Are you sure you want to delete this table?',
        yesLabel: 'Delete',
        noLabel: 'Cancel',
      });
      if (!isConfirmed) {
        return;
      }
      // ... API request ...
    }
    ```

- If confirmation content requires markup, we'd pass something like this to `confirm`:

    ```ts
    {
      title: 'Delete Table',
      content: {
        component: DeleteTableConfirmation,
        props: { tableId: id },
      },
      yesLabel: 'Delete',
      noLabel: 'Cancel',
    }
    ```

- Another interesting workflow mentioned [here](https://github.com/centerofci/mathesar/pull/650#pullrequestreview-787938023) is the case where we want to show a loading spinner after the user confirms the modal. My preference would be to deal with that case by using a separate (and very similar) system to display a modal loading spinner (with a message). Another approach would be to pass an async callback to `confirm`. But I like the separate system because a modal loading spinner won't have any cancel buttons or ways for the user to close it.

## Implementation notes

- Blocked by #750

### LINKED ISSUE #887: Table deletion is breaking on the frontend
## Description
Table deletion is implemented on the frontend, but there seems to be no action when user clicks on Table -> Delete.

## Expected behavior
When clicking Table -> Delete, it should open up a modal and prompt the user to delete the table.

## Additional context
`DeleteTableModal.svelte` has the delete confirmation modal to which isOpen is not passed. Binding it down should fix this issue.

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #759 
Fixes #755
Fixes #887 

## Summary

This PR gives us an easy way to display modal confirmation messages without creating any new components.

## Example code

```ts
confirm({
  title: 'Burn document?',
  body: [
    'It will be permanently destroyed.',
    'It may take some time to get the fire started.',
  ],
  proceedButton: { label: 'Burn', icon: { data: faFire } },
  onProceed: () => api.burn(),
  onSuccess: () => toast.success({ message: 'Document burned.' }),
  onError: (e) => toast.error({ message: `Unable to burn document. ${e.message}` }),
});
```

## Notes

- The `confirm` function returns a Promise that resolves to `true` if the user confirmed, or `false` if the user canceled.
    - We're free to utilize that Promise for control flow if we like, but the `confirm` function also acceps callbacks for control flow. One import reason to use callbacks is for the ascynchrous failure case because we want to keep the modal confirmation up and give the user the opportunity to press the proceed button again.

## Demo

From Storybook "Systems/Confirmation":

Peek 2021-11-23 13-22

## Review tips

- Play with deleting a table.
- Play with the modal confirmations within Storybook. 

    Start storybook with:

    `docker exec -it -w /code/mathesar_ui mathesar_service npm run storybook`

- Consider the design of the `confirm` function and its props to spot any red flags or potential pain points in developer experience of calling `confirm`. See available props by finding `interface ConfirmationProps`.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@pavish This PR is ready to go except for the failing tests. I'd really like to be able to these these linting errors. I tried using various forms of `eslint-disable` but I couldn't figure out a way to tell eslint to shut up. How do you recommend we proceed?

**Comment by dmos62** [comment]
> @pavish This PR is ready to go except for the failing tests. I'd really like to be able to these these linting errors. I tried using various forms of `eslint-disable` but I couldn't figure out a way to tell eslint to shut up. How do you recommend we proceed?

One quick and dirty way to fix that is to litter type casts, overriding Typescript's (failing) inference. Though, ideally, you'd extend Typescript compiler's ability to understand Svelte's reactive syntax, so I'd look into that as well. I bet @pavish will have more insight though.

**Comment by seancolsen** [comment]
@pavish in b16586558a7bc270ccdb82e2f49aee9ac1424de5 I'm proposing we address the linting problem here by turning off those rules for Svelte files. I can revert that commit if you'd like to take a different approach.

**Comment by pavish** [comment]
@seancolsen @dmos62 
The syntax,
```
$: ({ value1, value2 } = object);
```
causes these linting errors. When the linter encounters this syntax in svelte component, it transforms it to the following:
```
let value;
let value2;

({ value1, value2 } = object);
```
and then applies the linting rules over it. This leads to TS linting rules to throw warnings since value1 and value2 are assumed to be of type `any`.

A mess of a workaround is to do the following:
```
let object: ObjectType;
let value1: Type1;
let value2: Type2;
$: ({ value1, value2 } = object);
```
When the linter encounters this, it does not have to declare any variables and this would satisfy the TS rules.

This workaround applies _only_ for reactive variables. The linter down right _does not work_ well with TS rules when stores are involved.

Regarding https://github.com/centerofci/mathesar/pull/836#issuecomment-976995595: Ensuring `no-unsafe-assignment` and `no-unsafe-call` are some of the core reasons for using TS. I've so far been reluctant to disable these rules in svelte components.

I hoped the PR https://github.com/sveltejs/eslint-plugin-svelte3/pull/126 would be merged thereby fixing these issues. But it's been open for a couple months now and I don't see it being merged anytime soon.

So, I'm okay with disabling `no-unsafe-assignment` and `no-unsafe-call` for svelte components for now.

**Comment by seancolsen** [comment]
I added some more commits to this PR which begin to integrate the modal confirmation system into the app. You can now see it in action when deleting a table.

Peek 2021-11-30 19-58

**Comment by mr-gabe49** [comment]
Hey @seancolsen, are you planning to apply all the improvements from #755 in this PR? It seems you've already handled some of them.

**Comment by seancolsen** [comment]
@pavish Oh cool -- I wasn't thinking about #755. Yes, all of those bullet points _should_ be addressed here now.

**Comment by mr-gabe49** [comment]
@seancolsen Sounds good, I'll remove myself from #755.

File: mathesar_ui/src/component-library/confirmation/Confirmation.svelte [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+  function onClose() {
+    // When the user closes the confirmation modal by clicking on the "X" button
+    // we want to resolve the promise.
+    //
+    // In a "proceed" situation, we call `$resolve(true)` first and _then_ close
+    // the modal afterwards. Here, we're calling `deny()` no matter what
+    // happened, which means `deny()` we'll ultimately call `$resolve(true)`
+    // and then `$resolve(false)` which may seem a bit strange. This is fine
+    // because though because a Promise can only be resolved once.
+    $resolve(false);
```
Comment (pavish) [inline mathesar_ui/src/component-library/confirmation/Confirmation.svelte:52]: This is a hacky solution. While this would work perfectly fine, I'd rather have us think of better ways to handle this.

Having said that, I don't think we need to spend further time on this at the moment, and could safely put it off for later.

**Review by pavish — APPROVED** [review]
@seancolsen The PR looks good to me!
