### PR TITLE
Install.sh usablity fixes

### LINKED ISSUE #2570: Installation usability test - issues with install script
- [x] Issues from [WB testing report](https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/edit)
  - [x] DOCKER VERSION CHECK - too many spaces
  - [x] DATABASE CREDENTIALS - There should be an explanation that the credentials are valid for BOTH databases.
  - [x] CONFIGURATION DIRECTORY
    - [x] Change text to “The environment file will be installed at /etc/mathesar/.env” 
    - [x] Set directory permissions to `0640`
  - [x] DOCKER SETUP
    - [x] Add confirmation prompt  
  - [x] Remove example.com from superuser setup
- [x] Screenshot 1 - We need some space after "Enter the password" – configuring the local DB should be a different step or at least separated better.
- [x] Screenshot 2 - DISPLAY variable warning
- [x] ~Screenshot 3 - `43/20` is disconcerting~ wontfix

### Moved to other issues
- #2614
- #2615
- #2617

### Screenshot 1
Screen Shot 2023-02-24 at 2 20 51 PM

### Screenshot 2
Screen Shot 2023-02-24 at 2 30 17 PM

### Screenshot 3
Screen Shot 2023-02-24 at 2 30 56 PM

### Screenshot 4
Screen Shot 2023-02-24 at 2 44 40 PM

### PR DESCRIPTION
**Pull request by silentninja**
Fixes #2570
Contains the following fixes:
```
-  DOCKER VERSION CHECK - too many spaces
-  CONFIGURATION DIRECTORY
   - Change text to “The environment file will be installed at /etc/mathesar/.env”
   - Set directory permissions to 0640
-  DOCKER SETUP
   - Add confirmation prompt
-  Remove example.com from the superuser setup
- We need some space after "Enter the password" – configuring the local DB should be a different step or at least separated better.
- DISPLAY variable warning
```

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [ ] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -26,11 +26,13 @@ get_password () {
   local password
   local prompt="${1}: "
   local retry_prompt="
-The password cannot be empty!
+The password not be empty and must contain at least 1 uppercase, lowercase, number and special characters.
 ${prompt}"
   read -rs -p "${prompt}" password
-  until [ -n "${password}" ]; do
+  echo "$password" | grep "[A-Z]" | grep "[a-z]" | grep "[0-9]" | grep "[@#$%^&*]"
+  while [ -z "${password}" ] || [ $? -ne 0 ]; do
```
Comment (silentninja) [inline install.sh:33]: @mathemancer The conditions don't work correctly any idea?

Comment (mathemancer) [reply install.sh:33]: A few things:
- Password rules like this are a mistake in the first place.
- `[ -z "${password}" ]` overrides `[ $? -ne 0 ]`
  - If the password is missing some required character, but is non-zero length, the `$?` in the second check is 1 because `[ -z "${password}" ] returns 1

Comment (mathemancer) [reply install.sh:33]: Actually "overrides" is imprecise. The `[ $? -ne 0 ]` actually just negates whatever is put out by `[ -z "${password}" ]`

**Review by mathemancer — COMMENTED** [review]
Finishing review so pending comments are visible.

File: install.sh [hunk 2]
```diff
@@ -47,10 +47,10 @@ get_password () {
   local password
   local prompt="${1}: "
   local retry_prompt="
-The password cannot be empty!
+The password must contain minimum of 8 characters!
 ${prompt}"
   read -rs -p "${prompt}" password
-  until [ -n "${password}" ]; do
+  until [ ${#password} -ge 8 ]; do
```
Comment (mathemancer) [inline install.sh:53]: We can't demand a minimum password length when the user is connecting to a preexisting DB

File: install.sh [hunk 3]
```diff
@@ -95,6 +95,7 @@ configure_db_urls () {
     db_name=$(get_nonempty "${prefix} database name" "${default_db}")
     enc_db_name=$(percent_encode_reserved "${db_name}")
   fi
+  echo "Note: We will be using the same user credentials across all the databases created by Mathesar"
```
[the remark this answers is not in the document]
Comment (silentninja) [reply install.sh:98]: The note mentions **using** the same user credentials for databases **created by Mathesar** only

**Review by mathemancer — COMMENTED** [review]
Found another issue.

File: install.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (mathemancer) [reply install.sh:98]: Sure, but that's confusing when creating credentials for another DB, and even moreso when it's printed twice.

**Comment by mathemancer** [comment]
I reverted the minimum password length check, since I'm not confident I can fix it right now. We should handle it in a separate issue / PR.

**Review by mathemancer — COMMENTED** [review]
Okay, I think we should merge with these modifications.

**Review by mathemancer — APPROVED** [review]
Previous review should have been an approval.
