### PR TITLE
Copy formatted cell values to clipboard instead of raw values

### LINKED ISSUE #3085: Copying FK cells should copy the record summary instead of the PK value
## Steps to reproduce

Copy these cells...

image

- On the latest `develop`, I get:

    ```
    1	3	175
    2	529	172
    3	5	4
    ```

    (bad)

- Whereas, when I checkout 71485c1739558fd94d460b41f95d0055e4e6e2a2, I get get:

    ```
    1	FDD6-C43D-82BC-9ABA	Mark
    2	D2E1-9ED6-0778-83D7	Michelle
    3	5117-5964-EFE9-534E	Brooke
    ```

    (good)

I'd venture to guess this regression is due to [this change of mine](https://github.com/centerofci/mathesar/pull/2867/files#diff-e888a63e65bafac463d1242476bfe50bef0cee112529cbbc8a70a7d470702099R127).

## Additional context

- Bug introduced by @seancolsen in #2867
- Originally reported by @ghislaineguerin in #3080

### PR DESCRIPTION
**Pull request by seancolsen**
Fixes #3085

## Notes

- b288c53dca0d8e2eee70f8fab004bb9c93439eb3 is the change which actually fixes the bug. It's a very small change.
- The bug is from a mistake I made while implementing #2867, partly because I was also working to lay some groundwork for #2812. To support pasting cell values in a robust manner, we need to copy the formatted cell value and the raw cell value. That's why I had code to handle both of these sorts of values. But the code wasn't actually using both values before, which may have been a little confusing.
- In this PR I've gone ahead and implemented some of the remaining logic so as to make this existing code a bit clearer. I did a little refactoring along the way to improve code cleanliness.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by seancolsen** [comment]
@ghislaineguerin you might also be interested in looking at this since it addresses an issue you [originally](https://github.com/centerofci/mathesar/issues/3080) reported.

File: mathesar_ui/src/components/sheet/SheetClipboardHandler.ts [hunk 1]
```diff
@@ -107,42 +111,63 @@ export class SheetClipboardHandler<
...
+          recordSummaries,
+        );
+        const type = column.abstractType.identifier;
+        structuredRow.push({
+          type,
+          raw: rawCellValue,
+          formatted: formattedCellValue,
+        });
+        tsvRow.push(formattedCellValue);
       }
```
Comment (pavish) [inline mathesar_ui/src/components/sheet/SheetClipboardHandler.ts:151]: A minor nitpick.

For cases like these, where we don't have break out of the loop, I'd prefer iterating with `forEach` and `return` statements instead of a for loop and `continue`.

I don't have a major concern towards removing the `no-continue` rule, but I'm not a fan of `continue` either.

No action item needed. I only wanted to share this.

**Review by pavish — APPROVED** [review]
Looks good!
