### PR TITLE
Fix url sync and reorganize Tab store

### LINKED ISSUE #651: Refactor frontend stores for table-data
## Purpose of this refactor:
1. Our tableData store handles colums, records and meta information needed for parameters and display purposes. It also includes the type definitions for all of them. This makes it cluttered, and there is an overlap of different concerns.
A better approach would be to split it into separate stores, and have a parent store which maintains the rest.
2. Currently, logic of certain requirements such passing parameters to table record request, refetching table data when params change etc., are done on the component. This can be side stepped and done entirely by observing store values. This gives a cleaner view/data model.
3. We need to simplify certain display specific stores such as column position map, to improve readability.
4. General improvements, separate out cells from header and row as different components.
5. Update svelte, vite and related packages.

### PR DESCRIPTION
**Pull request by pavish**
Fixes #651 

**Technical details**
* Fixes broken sync between open tabs and URL. Copying and pasting the URL will retain state for below configurations:
    - Open and active tabs
    - Pagination
    - Filters
    - Sort
    - Groups
* Handles url sync only from the tab context and not the table context
* Reogranizes tabular data base exports with a TabularData class and a manager
* Reorganizes Tab store
  - Adds tabularData as part of tab
* Creates an EventHandler base class
  - Columns and TabularData classes extend this

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: mathesar_ui/src/stores/table-data/columns.ts [hunk 1]
```diff
@@ -67,7 +68,7 @@ function api(url: string) {
   };
 }
 
-export class ColumnsDataStore implements Writable<ColumnsData> {
+export class ColumnsDataStore extends EventHandler implements Writable<ColumnsData> {
```
Comment (seancolsen) [inline mathesar_ui/src/stores/table-data/columns.ts:71]: Small note...

Generally I lean towards using composition over inheritance as much as possible. So for a situation like this I'd be inclined to add an `eventHandler` property on `ColumnsDataStore` instead of having `ColumnsDataStore` inherit from `EventHandler`.  That said, I recognize there are situations where inheritance is a better fit. I don't know this code deeply enough to have a well-formed opinion of whether inheritance is best for this case but just wanted to mention this opinion generally. We could always refactor this to use composition later on if needed.

**Review by seancolsen — APPROVED** [review]
This looks really good. I'm happy to see all the store refactoring here.

I played with these changes quite a bit and couldn't find a way to break them. My reading of the diff is a bit more cursory, given that a lot of the code changed is code I still haven't yet familiarized myself with. But I feel confident-enough in these changes that I think it's ready to merge when the tests pass.

File: mathesar_ui/src/stores/table-data/columns.ts (hunk 1 above)
Comment (pavish) [reply mathesar_ui/src/stores/table-data/columns.ts:71]: > Generally I lean towards using composition over inheritance as much as possible

This is also my preferred approach when there is a clear separation of concerns.

> I'd be inclined to add an `eventHandler` property on `ColumnsDataStore`

Composition would not be a good idea in this particular case.

If we have an `eventHandler` property, we would have to expose it. So we'd do `columnsDataStore.eventHandler.on('event', value);`. However, this also leads to exposing properties we wouldn't want to expose, such as `eventHandler.dispatch` and `eventHandler.destroy`.

The other possible way is to make `eventHandler` private, and have a wrapper method for `eventHander.on` on the `ColumnsDataStore` class. This would be boilerplate code we'd have to add in all the classes have need an event handler.

Inheritance works perfectly for such situations. We can decide this on a case by case basis and I don't think we should always lean towards a particular approach.
