### PR TITLE
Set currentIndex equal to selected item only if selected item is within options

### LINKED ISSUE #609: UpArrow does not work in the group section dropdown when data is grouped.
## Description

- When a user groups data by more than one column, the UpArrow in the 'add new group column' button does not work initially. 

## Expected behavior

- When the dropdown is open and a user clicks the upArrow the last item in the dropdown list should be focused. 

## To Reproduce

- Group data by a specific column
- Click on 'add new group column' button
- Click to open dropdown 
- Press UpArrow

## Environment
 - Browser: Chrome
## Additional context

Screenshot (16)

### PR DESCRIPTION
**Pull request by mr-gabe49**
Fixes #609 

- Adds an if statement to make sure currentIndex is set to selected item only if selected item is present within the dropdown list elements. 

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: mathesar_ui/src/components/select/Select.svelte [hunk 1]
```diff
@@ -45,7 +45,9 @@
   }
 
   function setSelectedItem() {
-    currentIndex = options.indexOf(value);
+    if (options.some((e) => e.label === value[labelKey])) {
```
Comment (pavish) [inline mathesar_ui/src/components/select/Select.svelte:48]: The idKey exists for the sole purpose of acting as the identifier for an option, in cases of checking conditions as such.

We can change this to:
```suggestion
    if (options.some((e) => e[idKey] === value?.[idKey])) {
```

**Review by pavish — CHANGES_REQUESTED** [review]

File: mathesar_ui/src/components/select/Select.svelte [hunk 2]
```diff
@@ -45,7 +45,9 @@
   }
 
   function setSelectedItem() {
-    currentIndex = options.indexOf(value);
+    if (options.some((e) => e[idKey] === value?.[idKey])) {
+      currentIndex = options.indexOf(value);
+    }
```
Comment (pavish) [inline mathesar_ui/src/components/select/Select.svelte:50]: @mr-gabe49 Sorry for not catching this earlier.

The value object need not necessarily be equal to the one in options. They may hold the same values of idKey and valueKey, but be two different objects. So, checking indexOf will return -1, even though we would expect it to return a value.

A better way to do this will be to:

```suggestion
   const index = options.findIndex((e) => e[idKey] === value?.[idKey]);
    if (index > -1) {
      currentIndex = index;
    }
```

**Review by pavish — CHANGES_REQUESTED** [review]

File: mathesar_ui/src/components/select/Select.svelte (hunk 2 above)
Comment (mr-gabe49) [reply mathesar_ui/src/components/select/Select.svelte:50]: @pavish Interesting, I'll go ahead and fix it. That's always the case even if the value is set using the options object?

Comment (pavish) [reply mathesar_ui/src/components/select/Select.svelte]: @mr-gabe49 No. When the value is set using the options object, it's not the case, because the memory reference for the entries would be the same.

But in some cases, like when the page initially loads (when a filter or group is already applied), we do not set the value from the options. We directly set it based on the url. In such cases, the memory references vary, i.e. the entry within options array would be a different object from the value.

**Review by pavish — APPROVED** [review]

File: mathesar_ui/src/components/select/Select.svelte (hunk 2 above)
Comment (mr-gabe49) [reply mathesar_ui/src/components/select/Select.svelte]: Got it, Thanks!
