### PR TITLE
Navbar navigates to import preview page for tables with unconfirmed imports

### LINKED ISSUE #2110: Prevent navigating to the Table Page for an unconfirmed import
## Steps to reproduce

1. Begin creating a new table by importing data.
1. When you get to the seconds step ("Finish setting up your table"), navigate back to the schema page.
1. Navigate to the table page for another table in the schema.
1. From that other table page, open the table selector in the navigation header.
1. Expect either:
    - that the list of tables does not contain the partially-imported table.

        _or_

    - that the list of tables _does_ contain the partially imported table, but that the table displays an asterisk (to indicate that its import process is incomplete) and that clicking on the entry for the table navigates to the import confirmation page.

1. Instead, observe that the partially-imported table displays in the list without an asterisk, and that clicking on the table navigates to the table page.

## Implementation ideas

- I think it might be best to fix this by redirecting the table page to the import confirmation page if the table is partially imported.

CC @pavish for thoughts on implementation

CC @ghislaineguerin and @kgodey for opinions on which of the two expectation scenarios described above might make more sense for users.

### PR DESCRIPTION
**Pull request by rajatvijay**
Fixes #2110 

**Technical details**
1. Created a new function `getLinkForTableItem` that returns a link but takes into consideration if the table has import confirmation pending.
2. Started using `<TableName table={entry.table} />` in `BreadcrumbSelectorRow` instead of the `NameWithIcon` component directly. 

**Screenshots**

Screenshot 2023-01-24 at 7 04 26 PM
Screenshot 2023-01-24 at 7 03 41 PM

## Checklist
 
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `master` branch of the repository
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

File: mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte [hunk 1]
```diff
@@ -13,9 +14,13 @@
...
-    <NameWithIcon {icon}>
-      <MatchHighlighter text={label} substring={filterString} />
-    </NameWithIcon>
+    {#if 'table' in entry}
+      <TableName table={entry.table} />
+    {:else}
+      <NameWithIcon {icon}>
+        <MatchHighlighter text={label} substring={filterString} />
+      </NameWithIcon>
+    {/if}
```
Comment (seancolsen) [inline mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte:23]: With this change we lose the match highlighting functionality.

- Before

    image

- After

    image

Can you fix this?

**Review by seancolsen — CHANGES_REQUESTED** [review]
One change requested

File: mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte (hunk 1 above)
Comment (seancolsen) [reply mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte]: Looks good!

**Review by seancolsen — APPROVED** [review]
:+1:
